"""changed db

Revision ID: 11fc4b6d2ea0
Revises: 978a724748b0
Create Date: 2026-03-24 12:04:15.621727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11fc4b6d2ea0'
down_revision: Union[str, Sequence[str], None] = '978a724748b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_raw_data',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('signature_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('device_address', sa.String(length=50), nullable=True),
    sa.Column('request_type', sa.Integer(), nullable=True),
    sa.Column('is_location', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.TEXT(), nullable=True),
    sa.Column('longitude', sa.TEXT(), nullable=True),
    sa.Column('peripherals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('created_at', 'signature_id')
    )
    op.drop_index(op.f('system_metrics_created_at_idx'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('service_status_created_at_idx'), table_name='service_status')
    op.drop_table('service_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_status',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('created_at', 'hostname', 'service_name', name=op.f('service_status_pkey'))
    )
    op.create_index(op.f('service_status_created_at_idx'), 'service_status', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('system_metrics',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpu_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpu_thershold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ram_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ram_free', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ram_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ram_thershold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disk_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disk_free', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('disk_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disk_thershold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('created_at', 'hostname', name=op.f('system_metrics_pkey'))
    )
    op.create_index(op.f('system_metrics_created_at_idx'), 'system_metrics', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_table('device_raw_data')
    # ### end Alembic commands ###
