"""changed db

Revision ID: 96c13cdd611d
Revises: 
Create Date: 2026-03-23 22:57:55.964333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c13cdd611d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_status',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('created_at', 'hostname')
    )
    op.create_table('system_metrics',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('cpu_usage', sa.Integer(), nullable=True),
    sa.Column('cpu_status', sa.Integer(), nullable=True),
    sa.Column('cpu_thershold', sa.Integer(), nullable=True),
    sa.Column('ram_usage', sa.Integer(), nullable=True),
    sa.Column('ram_free', sa.Float(), nullable=True),
    sa.Column('ram_status', sa.Integer(), nullable=True),
    sa.Column('ram_thershold', sa.Integer(), nullable=True),
    sa.Column('disk_usage', sa.Integer(), nullable=True),
    sa.Column('disk_free', sa.Float(), nullable=True),
    sa.Column('disk_status', sa.Integer(), nullable=True),
    sa.Column('disk_thershold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('created_at', 'hostname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_metrics')
    op.drop_table('service_status')
    # ### end Alembic commands ###
