"""fix varchar length

Revision ID: de9bee88e9f0
Revises: 03cbe15f041b
Create Date: 2026-03-23 22:13:03.344535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de9bee88e9f0'
down_revision: Union[str, Sequence[str], None] = '03cbe15f041b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('cpu_usage', sa.Integer(), nullable=True),
    sa.Column('cpu_status', sa.Integer(), nullable=True),
    sa.Column('ram_usage', sa.Integer(), nullable=True),
    sa.Column('ram_free', sa.Float(), nullable=True),
    sa.Column('ram_status', sa.Integer(), nullable=True),
    sa.Column('disk_usage', sa.Integer(), nullable=True),
    sa.Column('disk_free', sa.Float(), nullable=True),
    sa.Column('disk_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.drop_index(op.f('server_metrics_time_idx'), table_name='server_metrics')
    op.drop_table('server_metrics')
    op.drop_index(op.f('users_login_time_idx'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'login_time', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_login_time_idx'), 'users', [sa.literal_column('login_time DESC')], unique=False)
    op.create_table('server_metrics',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ram_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disk_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('server_metrics_time_idx'), 'server_metrics', [sa.literal_column('time DESC')], unique=False)
    op.drop_table('system_metrics')
    op.drop_table('service_status')
    # ### end Alembic commands ###
